### ISSUE TITLE
ModuleNotFoundError: No module named 'daal4py'

### ISSUE THREAD

**Issue by RisabBiswas** [intel/AiKit-code-samples#1]
This issue I found while running the sample code from AI Analytics toolkit.

How to Resolve:- 
1. Make sure you have the Intel Optimized Python Installed in yoo current working environment.
2. There might be some misleading solutions that will ask you to do a lot but it's really simple to resolve.
3. Once you make sure that you are good with the point no. 1 just install the daal4py using "Conda Install daal4py".
4. DAAL is actually the Intel's Data Analytics Acceleration Library, that contains the optimized models for your test code.

**Comment by ArunJose-Intel** [comment]
The Intel AI analytics toolkit has DAAL4PY and  Intel Optimized Python available along with the toolkit. The AI analytics toolkit  has three conda environments prepackaged with it namely "root" "tensorflow" and "pytorch". In these environments  "root" has DAAL4PY package preinstalled 
Usage:(Assuming AI analytics toolkit is installed in your machine)

1)set up your oneAPI environment with the setvars.sh script.
eg: `/opt/intel/inteloneapi/setvars.sh`
2)root environment will be activated by default. However, if you activated another environment, you can return with the following command
`source activate root`
3)Now you can run your code having daal4py using the below command
`python daal4py_HelloWorld.py`

**Comment by nathan-greeneltch-intel** [comment]
@RisabBiswas  This issue was a known issue in first version of AI Kit release. It has since been fixed. Newest version of oneAPI AI kit should not show this problem anymore.
